/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaovirtual.gui;

import salaovirtual.gui.tableModel.ForcedListSelectionModel;
import salaovirtual.gui.tableModel.ProdutoFornecimentoTableModel;
import salaovirtual.gui.tableModel.ConsultaFornecimentoTableModel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import salaovirtual.Compra;
import salaovirtual.Fornecedor;
import salaovirtual.Produto;
import salaovirtual.acesso.Consulta;

/**
 * Classe interna para um JDialog para consulta de fornecimento
 * 
 * @author Rafael Tavares
 */ 
public class ConsultaFornecedorFornecimentoModal extends javax.swing.JDialog {
    Fornecedor fornecedor;    
    private List<Integer> quantidade; // quantidade de compra
    private List<Produto> produtos; // produto de compra
    private List<Float> valores; // valor de compra
    
    /**
    * Construtor da classe
    * @param parent
    * @param modal 
    */   
    public ConsultaFornecedorFornecimentoModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon img = new ImageIcon(MenuInicial.class.getResource("/images/background/mini-icon.png"));
        this.setIconImage(img.getImage());
        Consulta con = new Consulta();
        this.fornecedor = con.encontrarFornecedor(1);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.PINK);
        tblFornecimento.setSelectionModel(new ForcedListSelectionModel());
        tblFornecimento.setModel(new ConsultaFornecimentoTableModel(this.getFornecedor()));
        gerarTabelaFornecimento();
        tblFornecimentoProduto.setSelectionModel(new ForcedListSelectionModel());
        tblFornecimentoProduto.setModel(new ProdutoFornecimentoTableModel(null, null, null));
        gerarTabelaProduto();
        
    }

    /**
     * Método para auxiliar a gerar uma nova tabela
     */
    private void gerarTabelaProduto() {
        tblFornecimentoProduto.getTableHeader().setFont(new Font("Courie", Font.BOLD, 15));
        tblFornecimentoProduto.getColumnModel().getColumn(0).setMaxWidth(65);
        tblFornecimentoProduto.getColumnModel().getColumn(2).setMaxWidth(130);
        tblFornecimentoProduto.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(4).setMaxWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(4).setPreferredWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(5).setMaxWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(5).setPreferredWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(6).setMaxWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(6).setPreferredWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(7).setMaxWidth(120);
        tblFornecimentoProduto.getColumnModel().getColumn(7).setPreferredWidth(120);
    }

    /**
     * Método para auxiliar a gerar uma nova tabela
     */
    private void gerarTabelaFornecimento() {
        tblFornecimento.getTableHeader().setFont(new Font("Courie", Font.BOLD, 15));
    }
    
    /**
     * Retorna o fornecedor que teve seus fornecimentos listados
     * @return Fornecedor
     */
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    /**
     * Define o fornecedor a ter seus fornecimentos listados
     * @param f 
     */
    public void setFornecedor(Fornecedor f) {
        this.fornecedor = f;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecimento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecimentoProduto = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Cliente");
        setResizable(false);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"))); // NOI18N
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkMouseReleased(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("Fornecimento");

        tblFornecimento.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        tblFornecimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFornecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecimentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecimento);

        tblFornecimentoProduto.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        tblFornecimentoProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblFornecimentoProduto);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel6.setText("Produtos do Fornecimento");

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel7.setText("Selecione um fornecimento para ver os produtos fornecidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel7)))
                .addGap(0, 306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(480, 480, 480))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(428, 428, 428))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(314, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseEntered

    private void btnOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseExited

    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Pressed.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMousePressed

    private void btnOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void tblFornecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecimentoMouseClicked
        if (tblFornecimento.getSelectedRow() != -1 ) {
            
            Consulta con = new Consulta();
            Compra c = con.encontrarCompra((Integer) tblFornecimento.getValueAt(tblFornecimento.getSelectedRow(), 0));
            produtos = new ArrayList();
            quantidade = new ArrayList();
            valores = new ArrayList();
            for (int i = 0; i < c.getProdutos().size(); i++) {
                produtos.add(con.encontrarProduto(c.getProdutos().get(i)));
            }
            quantidade = c.getQuantidade();
            valores = c.getValores();
            tblFornecimentoProduto.setModel(new ProdutoFornecimentoTableModel(produtos, quantidade, valores));
            gerarTabelaProduto();
        }
    }//GEN-LAST:event_tblFornecimentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedorFornecimentoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedorFornecimentoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedorFornecimentoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedorFornecimentoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaFornecedorFornecimentoModal dialog = new ConsultaFornecedorFornecimentoModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFornecimento;
    private javax.swing.JTable tblFornecimentoProduto;
    // End of variables declaration//GEN-END:variables
}
