/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaovirtual.gui;

import salaovirtual.exceptions.TipoDeCartaoInvalidoException;
import java.awt.Color;
import javax.swing.ImageIcon;
import salaovirtual.Cartao;
import salaovirtual.Cliente;
import salaovirtual.Dinheiro;
import salaovirtual.Funcionario;
import salaovirtual.acesso.Consulta;

/**
 * Classe interna para um JDialog que lê o funcionário e cliente para finalizar a venda
 * 
 * @author Rafael Tavares
 */ 
public class FinalizarVendaModal extends javax.swing.JDialog {

    private boolean finalizada;
    private Cliente cliente;
    private Funcionario funcionario;
    private Cartao cartao;
    private Dinheiro dinheiro;
    private float valorTotal;
    private float valorOriginal;
    
    /**
     * Cria um novo JDialog para o FinalizarVendaModal
     * @param parent
     * @param modal
     * @param f - funcionário logado
     * @param v - valor da venda
     */
    public FinalizarVendaModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.PINK);
        this.setLocationRelativeTo(null);
        this.setFinalizada(false);
        txtNomeFuncionario.setDisabledTextColor(Color.black);
        txtNomeCliente.setDisabledTextColor(Color.black);
        rdbGrupoPagamento.add(rdbCartao);
        rdbGrupoPagamento.add(rdbDinheiro);
        rdbCartao.setSelected(true);
        pnlDinheiro.setVisible(false);
        Cartao c = new Cartao();
        try {
            c.setTipo("Débito");
            valorTotal = c.getTaxa() * valorOriginal;
        } catch (TipoDeCartaoInvalidoException ex) {
            //
        }
        /*this.txtLoginFuncionario.setText(f.getLogin());
        this.txtNomeFuncionario.setText(f.getNome());
        funcionario = f;
        valorOriginal = v;*/
        lblValorTotal.setText("R$ " + valorTotal);
        lblValorParcela.setText("de R$ " + valorTotal);
    }
    
    /**
     * Define true se a venda foi finalizada, false se foi cancelada
     * @param f 
     */
    private void setFinalizada(boolean f) {
        this.finalizada = f;
    }
    
    /**
     * Retorna true se a venda foi finalizada, false se foi cancelada
     * @return Finalizada - true, cancelada - false
     */
    private boolean isFinalizada() {
        return this.finalizada;
    }

    /**
     * Define o funcionário da venda
     * @param f - funcionário
     */
    private void setFuncionario(Funcionario f) {
        this.funcionario = f;
    }
    
    /**
     * Retorna o funcionário da venda
     * @return Funcionario que realizou a venda
     */
    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    /**
     * Define o cliente da venda
     * @param c - cliente
     */
    private void setCliente(Cliente c) {
        this.cliente = c;
    }
    
    /**
     * Retorna o cliente da venda
     * @return Cliente que participou da venda
     */
    public Cliente getCliente() {
        return this.cliente;
    }

    /**
     * Define a forma de pagamento em cartão da venda
     * @param c - cartao
     */
    private void setCartao(Cartao c) {
        this.cartao = c;
    }
    
    /**
     * Retorna a forma de pagamento em cartão da venda
     * @return Cartao do pagamento
     */
    public Cartao getCartao() {
        return this.cartao;
    }

    /**
     * Define a forma de pagamento em dinheiro da venda
     * @param d - dinhero
     */
    private void setCartao(Dinheiro d) {
        this.dinheiro = d;
    }
    
    /**
     * Retorna a forma de pagamento em cartão da venda
     * @return Cartao do pagamento
     */
    public Dinheiro getDinheiro() {
        return this.dinheiro;
    }

    /**
     * Define o valor total da venda - pode ter mudado por causa das taxas do cartão
     * @param v - valor total da venda
     */
    private void setValorTotal(float v) {
        this.valorTotal = v;
    }
    
    /**
     * Retorna a forma de pagamento em cartão da venda
     * @return Cartao do pagamento
     */
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGrupoPagamento = new javax.swing.ButtonGroup();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnConsultarCliente = new javax.swing.JButton();
        btnConsultarFuncionario = new javax.swing.JButton();
        txtLoginFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        rdbDinheiro = new javax.swing.JRadioButton();
        rdbCartao = new javax.swing.JRadioButton();
        pnlDinheiro = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        lblTroco = new javax.swing.JLabel();
        pnlCartao = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbCartao = new javax.swing.JComboBox<>();
        txtQtdParcelas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblValorParcela = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Venda");
        setBackground(new java.awt.Color(249, 180, 209));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"))); // NOI18N
        btnOk.setToolTipText("");
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkMouseReleased(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okcancel/botaoCancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel3.setText("Código do Cliente");

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar.png"))); // NOI18N
        btnConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseReleased(evt);
            }
        });
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        btnConsultarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar.png"))); // NOI18N
        btnConsultarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarFuncionarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultarFuncionarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConsultarFuncionarioMouseReleased(evt);
            }
        });
        btnConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFuncionarioActionPerformed(evt);
            }
        });

        txtLoginFuncionario.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel5.setText("Login do Funcionário");

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel8.setText("Informações adicionais da venda");

        txtCodigoCliente.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel6.setText("Nome");

        txtNomeFuncionario.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        txtNomeFuncionario.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel7.setText("Nome");

        txtNomeCliente.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        txtNomeCliente.setEnabled(false);

        rdbDinheiro.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        rdbDinheiro.setText("Dinheiro");
        rdbDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDinheiroActionPerformed(evt);
            }
        });

        rdbCartao.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        rdbCartao.setText("Cartão");
        rdbCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCartaoActionPerformed(evt);
            }
        });

        pnlDinheiro.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel12.setText("Valor Recebido:");

        txtValorRecebido.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        txtValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyReleased(evt);
            }
        });

        lblTroco.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        lblTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroco.setText("Troco: R$ -");

        javax.swing.GroupLayout pnlDinheiroLayout = new javax.swing.GroupLayout(pnlDinheiro);
        pnlDinheiro.setLayout(pnlDinheiroLayout);
        pnlDinheiroLayout.setHorizontalGroup(
            pnlDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDinheiroLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(pnlDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDinheiroLayout.setVerticalGroup(
            pnlDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblTroco)
                .addContainerGap())
        );

        pnlCartao.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel9.setText("Pagamento");

        cmbCartao.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        cmbCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Débito", "Crédito" }));
        cmbCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCartaoActionPerformed(evt);
            }
        });

        txtQtdParcelas.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        txtQtdParcelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtdParcelas.setText("1");
        txtQtdParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdParcelasKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel13.setText("Parcelas");

        lblValorParcela.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        lblValorParcela.setText("de R$ -");

        javax.swing.GroupLayout pnlCartaoLayout = new javax.swing.GroupLayout(pnlCartao);
        pnlCartao.setLayout(pnlCartaoLayout);
        pnlCartaoLayout.setHorizontalGroup(
            pnlCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartaoLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cmbCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(pnlCartaoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtQtdParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorParcela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartaoLayout.setVerticalGroup(
            pnlCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQtdParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValorParcela))
                    .addComponent(jLabel13))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel10.setText("Pagamento");

        lblValorTotal.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotal.setText("Valor total: R$ ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnConsultarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addGap(208, 208, 208)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(rdbCartao)
                        .addGap(70, 70, 70)
                        .addComponent(rdbDinheiro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(pnlCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbCartao)
                    .addComponent(rdbDinheiro))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pnlCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(lblValorTotal)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseEntered

    private void btnOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseExited

    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Pressed.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMousePressed

    private void btnOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
        btnOk.setIcon(i);
    }//GEN-LAST:event_btnOkMouseReleased

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoCancelar_Hover.png"));
        btnCancelar.setIcon(i);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoCancelar.png"));
        btnCancelar.setIcon(i);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoCancelar_Pressed.png"));
        btnCancelar.setIcon(i);
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoCancelar_Hover.png"));
        btnCancelar.setIcon(i);
    }//GEN-LAST:event_btnCancelarMouseReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setFinalizada(false);
        cliente = null;
        funcionario = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConsultarFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarFuncionarioMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Hover.png"));
        btnConsultarFuncionario.setIcon(i);
    }//GEN-LAST:event_btnConsultarFuncionarioMouseEntered

    private void btnConsultarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarFuncionarioMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar.png"));
        btnConsultarFuncionario.setIcon(i);
    }//GEN-LAST:event_btnConsultarFuncionarioMouseExited

    private void btnConsultarFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarFuncionarioMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Pressed.png"));
        btnConsultarFuncionario.setIcon(i);
    }//GEN-LAST:event_btnConsultarFuncionarioMousePressed

    private void btnConsultarFuncionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarFuncionarioMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Pressed.png"));
        btnConsultarFuncionario.setIcon(i);
    }//GEN-LAST:event_btnConsultarFuncionarioMouseReleased

    private void btnConsultarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Hover.png"));
        btnConsultarCliente.setIcon(i);
    }//GEN-LAST:event_btnConsultarClienteMouseEntered

    private void btnConsultarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar.png"));
        btnConsultarCliente.setIcon(i);
    }//GEN-LAST:event_btnConsultarClienteMouseExited

    private void btnConsultarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Pressed.png"));
        btnConsultarCliente.setIcon(i);
    }//GEN-LAST:event_btnConsultarClienteMousePressed

    private void btnConsultarClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/images/cadastro/botaoConsultar_Hover.png"));
        btnConsultarCliente.setIcon(i);
    }//GEN-LAST:event_btnConsultarClienteMouseReleased

    private void btnConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarFuncionarioActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.setFinalizada(true);
        funcionario = null;
        cliente = null;
        txtNomeFuncionario.setText("");
        txtNomeCliente.setText("");
        Consulta con = new Consulta();
        if (txtLoginFuncionario.getText().length() != 0) {
            this.setFuncionario(con.encontrarFuncionarioLogin(txtLoginFuncionario.getText()));
            if (funcionario == null) {
                System.out.println("login funcionario invalido");
                return;
            }
            txtNomeFuncionario.setText(this.getFuncionario().getNome());
        }
        if (txtCodigoCliente.getText().length() != 0) {
            try{
                this.setCliente(con.encontrarCliente(Integer.parseInt(txtCodigoCliente.getText())));
                if (cliente == null) {
                    System.out.println("código cliente invalido");
                    return;
                }
                txtNomeCliente.setText(this.getCliente().getNome());
            } catch (NumberFormatException e) {
                System.out.println("código cliente invalido2");
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtValorRecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyReleased
        try {
            float valorRecebido = Float.parseFloat(txtValorRecebido.getText());
            if (valorRecebido >= this.getValorTotal()) {
                //lblTroco.setText("Troco: R$ " + valorRecebido - this.getValorTotal());
            }
            else {
                lblTroco.setText("Troco: R$ -");
            }
        } catch (NumberFormatException ex) {
            lblTroco.setText("Troco: R$ -");
        }
    }//GEN-LAST:event_txtValorRecebidoKeyReleased

    private void txtQtdParcelasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdParcelasKeyReleased
        try {
            int qtdParcelas = Integer.parseInt(txtQtdParcelas.getText());
            if (qtdParcelas >= 1) {
                lblValorParcela.setText("de R$ " + this.getValorTotal()/qtdParcelas);
            }
            else {
                lblValorParcela.setText("de R$ -");
            }
        } catch (NumberFormatException ex) {
            lblValorParcela.setText("de R$ -");
        }
    }//GEN-LAST:event_txtQtdParcelasKeyReleased

    private void cmbCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCartaoActionPerformed
        String tipo = (String) cmbCartao.getSelectedItem();
        try {
            cartao.setValorTotal(valorOriginal * cartao.getTaxa());
            lblValorTotal.setText("Valor Total: R$ " + cartao.getValorTotal());
        } catch (TipoDeCartaoInvalidoException ex) {
            //
        }
    }//GEN-LAST:event_cmbCartaoActionPerformed

    private void rdbCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCartaoActionPerformed
        String tipo = (String) cmbCartao.getSelectedItem();
        try {
            cartao.setValorTotal(valorOriginal * cartao.getTaxa());
            lblValorTotal.setText("Valor Total: R$ " + cartao.getValorTotal());
        } catch (TipoDeCartaoInvalidoException ex) {
            //
        }
    }//GEN-LAST:event_rdbCartaoActionPerformed

    private void rdbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDinheiroActionPerformed
        lblValorTotal.setText("Valor Total: R$ " + valorOriginal);
    }//GEN-LAST:event_rdbDinheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarVendaModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarVendaModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarVendaModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarVendaModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FinalizarVendaModal dialog = new FinalizarVendaModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    /**
     * Classe interna para um JDialog que exibe uma mensagem e possui apenas o botão OK
     * 
     * @author Rafael Tavares
     */ 
    public class MensagemOkModal extends javax.swing.JDialog {
        
        
        /**
         * Construtor da classe
         * @param parent
         * @param modal 
         */
        public MensagemOkModal(java.awt.Frame parent, boolean modal, String mensagem, String titulo) {
            super(parent, modal);
            initComponents();
            this.getContentPane().setBackground(Color.PINK);
            lblMensagem.setText(mensagem);
            this.setTitle(titulo);
            this.setLocationRelativeTo(null);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
            btnOk = new javax.swing.JButton();
            lblMensagem = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Erro");
            setResizable(false);

            btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"))); // NOI18N
            btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnOkMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnOkMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    btnOkMousePressed(evt);
                }
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    btnOkMouseReleased(evt);
                }
            });
            btnOk.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnOkActionPerformed(evt);
                }
            });

            lblMensagem.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
            lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblMensagem.setText("Nenhuma linha foi selecionadaaaaaaaaaaaaa");
            lblMensagem.setToolTipText("");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {                                   
            ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
            btnOk.setIcon(i);
        }                                  

        private void btnOkMouseExited(java.awt.event.MouseEvent evt) {                                  
            ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK.png"));
            btnOk.setIcon(i);
        }                                 

        private void btnOkMousePressed(java.awt.event.MouseEvent evt) {                                   
            ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Pressed.png"));
            btnOk.setIcon(i);
        }                                  

        private void btnOkMouseReleased(java.awt.event.MouseEvent evt) {                                    
            ImageIcon i = new ImageIcon(getClass().getResource("/images/okcancel/botaoOK_Hover.png"));
            btnOk.setIcon(i);
        }                                   

        private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {                                      
            this.dispose();
        }                

        // Variables declaration - do not modify                     
        private javax.swing.JButton btnOk;
        private javax.swing.JLabel lblMensagem;
        // End of variables declaration                   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarFuncionario;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cmbCartao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorParcela;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlCartao;
    private javax.swing.JPanel pnlDinheiro;
    private javax.swing.JRadioButton rdbCartao;
    private javax.swing.JRadioButton rdbDinheiro;
    private javax.swing.ButtonGroup rdbGrupoPagamento;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtLoginFuncionario;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtQtdParcelas;
    private javax.swing.JTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables
}
