/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaovirtual;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author rafae
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServicos = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblFornecimento = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoServico.png"))); // NOI18N
        lblServicos.setMaximumSize(new java.awt.Dimension(121, 64));
        lblServicos.setMinimumSize(new java.awt.Dimension(121, 64));
        lblServicos.setPreferredSize(new java.awt.Dimension(121, 64));
        lblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblServicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblServicosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblServicosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblServicosMouseReleased(evt);
            }
        });

        lblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoCliente.png"))); // NOI18N
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClientesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblClientesMouseReleased(evt);
            }
        });

        lblFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecedor.png"))); // NOI18N
        lblFornecedor.setMaximumSize(new java.awt.Dimension(137, 64));
        lblFornecedor.setMinimumSize(new java.awt.Dimension(137, 64));
        lblFornecedor.setName(""); // NOI18N
        lblFornecedor.setPreferredSize(new java.awt.Dimension(137, 64));
        lblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFornecedorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseReleased(evt);
            }
        });

        lblFornecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecimento.png"))); // NOI18N
        lblFornecimento.setMaximumSize(new java.awt.Dimension(155, 64));
        lblFornecimento.setMinimumSize(new java.awt.Dimension(155, 64));
        lblFornecimento.setPreferredSize(new java.awt.Dimension(155, 64));
        lblFornecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFornecimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFornecimentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFornecimentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFornecimentoMouseReleased(evt);
            }
        });

        lblProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoProduto.png"))); // NOI18N
        lblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProdutoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProdutoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblProdutoMouseReleased(evt);
            }
        });

        lblVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoVenda.png"))); // NOI18N
        lblVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVendaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVendaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblVendaMouseReleased(evt);
            }
        });

        lblFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/botaoFuncionario.png"))); // NOI18N
        lblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFuncionarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientes)
                    .addComponent(lblFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto)
                            .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncionario)
                            .addComponent(lblVenda))))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduto)
                    .addComponent(lblVenda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario))
                .addGap(18, 18, 18)
                .addComponent(lblFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblServicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServicosMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoServico_Hover.png"));
        this.lblServicos.setIcon(i);
    }//GEN-LAST:event_lblServicosMouseEntered

    private void lblServicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServicosMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoServico.png"));
        this.lblServicos.setIcon(i);
    }//GEN-LAST:event_lblServicosMouseExited

    private void lblServicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServicosMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoServico_Pressed.png"));
        this.lblServicos.setIcon(i);
    }//GEN-LAST:event_lblServicosMousePressed

    private void lblServicosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServicosMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoServico_Hover.png"));
        this.lblServicos.setIcon(i);
    }//GEN-LAST:event_lblServicosMouseReleased

    private void lblClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoCliente_Hover.png"));
        this.lblClientes.setIcon(i);
    }//GEN-LAST:event_lblClientesMouseEntered

    private void lblClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoCliente.png"));
        this.lblClientes.setIcon(i);
    }//GEN-LAST:event_lblClientesMouseExited

    private void lblClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoCliente_Pressed.png"));
        this.lblClientes.setIcon(i);
    }//GEN-LAST:event_lblClientesMousePressed

    private void lblClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoCliente_Hover.png"));
        this.lblClientes.setIcon(i);
    }//GEN-LAST:event_lblClientesMouseReleased

    private void lblFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecedor_Hover.png"));
        this.lblFornecedor.setIcon(i);
    }//GEN-LAST:event_lblFornecedorMouseEntered

    private void lblFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecedor.png"));
        this.lblFornecedor.setIcon(i);
    }//GEN-LAST:event_lblFornecedorMouseExited

    private void lblFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecedor_Pressed.png"));
        this.lblFornecedor.setIcon(i);
    }//GEN-LAST:event_lblFornecedorMousePressed

    private void lblFornecedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecedor_Hover.png"));
        this.lblFornecedor.setIcon(i);
    }//GEN-LAST:event_lblFornecedorMouseReleased

    private void lblFornecimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecimentoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecimento_Hover.png"));
        this.lblFornecimento.setIcon(i);
    }//GEN-LAST:event_lblFornecimentoMouseEntered

    private void lblFornecimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecimentoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecimento.png"));
        this.lblFornecimento.setIcon(i);
    }//GEN-LAST:event_lblFornecimentoMouseExited

    private void lblFornecimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecimentoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecimento_Pressed.png"));
        this.lblFornecimento.setIcon(i);
    }//GEN-LAST:event_lblFornecimentoMousePressed

    private void lblFornecimentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecimentoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFornecimento_Hover.png"));
        this.lblFornecimento.setIcon(i);
    }//GEN-LAST:event_lblFornecimentoMouseReleased

    private void lblProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoProduto_Hover.png"));
        this.lblProduto.setIcon(i);    }//GEN-LAST:event_lblProdutoMouseEntered

    private void lblProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoProduto.png"));
        this.lblProduto.setIcon(i);    }//GEN-LAST:event_lblProdutoMouseExited

    private void lblProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoProduto_Pressed.png"));
        this.lblProduto.setIcon(i);    }//GEN-LAST:event_lblProdutoMousePressed

    private void lblProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoProduto_Hover.png"));
        this.lblProduto.setIcon(i);
    }//GEN-LAST:event_lblProdutoMouseReleased

    private void lblVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoVenda_Hover.png"));
        this.lblVenda.setIcon(i);
    }//GEN-LAST:event_lblVendaMouseEntered

    private void lblVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoVenda.png"));
        this.lblVenda.setIcon(i);
    }//GEN-LAST:event_lblVendaMouseExited

    private void lblVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoVenda_Pressed.png"));
        this.lblVenda.setIcon(i);
    }//GEN-LAST:event_lblVendaMousePressed

    private void lblVendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendaMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoVenda_Hover.png"));
        this.lblVenda.setIcon(i);
    }//GEN-LAST:event_lblVendaMouseReleased

    private void lblFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFuncionario_Hover.png"));
        this.lblFuncionario.setIcon(i);
    }//GEN-LAST:event_lblFuncionarioMouseEntered

    private void lblFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFuncionario.png"));
        this.lblFuncionario.setIcon(i);
    }//GEN-LAST:event_lblFuncionarioMouseExited

    private void lblFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFuncionario_Pressed.png"));
        this.lblFuncionario.setIcon(i);
    }//GEN-LAST:event_lblFuncionarioMousePressed

    private void lblFuncionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/botaoFuncionario_Hover.png"));
        this.lblFuncionario.setIcon(i);
    }//GEN-LAST:event_lblFuncionarioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFornecimento;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblVenda;
    // End of variables declaration//GEN-END:variables
}
