/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaovirtual;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author rafae
 */
public class MenuInicial extends javax.swing.JFrame {

    private boolean cadastro = false;
    
    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        pnlSubMenu.setVisible(false);
        pnlSubMenu.setOpaque(false);
        pnlAgenda.setVisible(true);
        pnlAgenda.setOpaque(false);
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda_Hover.png"));
        btnMenuAgenda.setIcon(i);
        tblAgenda.setSelectionModel(new ForcedListSelectionModel());
        tblAgenda.setModel(new AgendaTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuAgenda = new javax.swing.JButton();
        btnMenuConsulta = new javax.swing.JButton();
        btnMenuServico = new javax.swing.JButton();
        btnMenuVenda = new javax.swing.JButton();
        btnMenuCadastro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlAgenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        btnAgendarServico = new javax.swing.JButton();
        btnCancelarServico = new javax.swing.JButton();
        pnlSubMenu = new javax.swing.JPanel();
        btnMenuFornecedor = new javax.swing.JButton();
        btnMenuFuncionario = new javax.swing.JButton();
        btnMenuFornecimento = new javax.swing.JButton();
        btnMenuProduto = new javax.swing.JButton();
        btnMenuCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenuAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda.png"))); // NOI18N
        btnMenuAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuAgendaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuAgendaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuAgendaMouseReleased(evt);
            }
        });
        btnMenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAgendaActionPerformed(evt);
            }
        });

        btnMenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuConsulta.png"))); // NOI18N
        btnMenuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuConsultaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuConsultaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuConsultaMouseReleased(evt);
            }
        });
        btnMenuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuConsultaActionPerformed(evt);
            }
        });

        btnMenuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuServico.png"))); // NOI18N
        btnMenuServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuServicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuServicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuServicoMouseReleased(evt);
            }
        });
        btnMenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuServicoActionPerformed(evt);
            }
        });

        btnMenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuVenda.png"))); // NOI18N
        btnMenuVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuVendaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuVendaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuVendaMouseReleased(evt);
            }
        });
        btnMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuVendaActionPerformed(evt);
            }
        });

        btnMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCadastro.png"))); // NOI18N
        btnMenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuCadastroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuCadastroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuCadastroMouseReleased(evt);
            }
        });
        btnMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCadastroActionPerformed(evt);
            }
        });

        jSeparator1.setToolTipText("");

        pnlAgenda.setAutoscrolls(true);
        pnlAgenda.setPreferredSize(new java.awt.Dimension(1290, 645));

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);

        btnAgendarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoAgendarServico.png"))); // NOI18N
        btnAgendarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendarServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendarServicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgendarServicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgendarServicoMouseReleased(evt);
            }
        });
        btnAgendarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarServicoActionPerformed(evt);
            }
        });

        btnCancelarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoCancelarServico.png"))); // NOI18N
        btnCancelarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarServicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarServicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarServicoMouseReleased(evt);
            }
        });
        btnCancelarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addComponent(btnAgendarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnCancelarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgendarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pnlSubMenu.setAutoscrolls(true);
        pnlSubMenu.setPreferredSize(new java.awt.Dimension(1290, 645));

        btnMenuFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecedor.png"))); // NOI18N
        btnMenuFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuFornecedorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuFornecedorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuFornecedorMouseReleased(evt);
            }
        });

        btnMenuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFuncionario.png"))); // NOI18N
        btnMenuFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuFuncionarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuFuncionarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuFuncionarioMouseReleased(evt);
            }
        });

        btnMenuFornecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecimento.png"))); // NOI18N
        btnMenuFornecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuFornecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuFornecimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuFornecimentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuFornecimentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuFornecimentoMouseReleased(evt);
            }
        });

        btnMenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuProduto.png"))); // NOI18N
        btnMenuProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuProdutoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuProdutoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuProdutoMouseReleased(evt);
            }
        });

        btnMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCliente.png"))); // NOI18N
        btnMenuCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuClienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuClienteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlSubMenuLayout = new javax.swing.GroupLayout(pnlSubMenu);
        pnlSubMenu.setLayout(pnlSubMenuLayout);
        pnlSubMenuLayout.setHorizontalGroup(
            pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubMenuLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSubMenuLayout.createSequentialGroup()
                        .addComponent(btnMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnMenuFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnMenuFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSubMenuLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnMenuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnMenuFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        pnlSubMenuLayout.setVerticalGroup(
            pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubMenuLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMenuFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMenuCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSubMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(btnMenuAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuServico, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenuConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuServico, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(pnlSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(111, Short.MAX_VALUE)
                    .addComponent(pnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAgendaMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda_Hover.png"));
        btnMenuAgenda.setIcon(i);
    }//GEN-LAST:event_btnMenuAgendaMouseEntered

    private void btnMenuAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAgendaMouseExited
        if (!pnlAgenda.isVisible()) {
            ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda.png"));
            btnMenuAgenda.setIcon(i);
        }
    }//GEN-LAST:event_btnMenuAgendaMouseExited

    private void btnMenuAgendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAgendaMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda_Pressed.png"));
        btnMenuAgenda.setIcon(i);
    }//GEN-LAST:event_btnMenuAgendaMousePressed

    private void btnMenuAgendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAgendaMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuAgenda_Hover.png"));
        btnMenuAgenda.setIcon(i);
    }//GEN-LAST:event_btnMenuAgendaMouseReleased

    private void btnMenuServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuServicoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuServico_Hover.png"));
        btnMenuServico.setIcon(i);
    }//GEN-LAST:event_btnMenuServicoMouseEntered

    private void btnMenuServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuServicoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuServico.png"));
        btnMenuServico.setIcon(i);
    }//GEN-LAST:event_btnMenuServicoMouseExited

    private void btnMenuServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuServicoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuServico_Pressed.png"));
        btnMenuServico.setIcon(i);
    }//GEN-LAST:event_btnMenuServicoMousePressed

    private void btnMenuServicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuServicoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuServico_Hover.png"));
        btnMenuServico.setIcon(i);
    }//GEN-LAST:event_btnMenuServicoMouseReleased

    private void btnMenuVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVendaMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuVenda_Hover.png"));
        btnMenuVenda.setIcon(i);
    }//GEN-LAST:event_btnMenuVendaMouseEntered

    private void btnMenuVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVendaMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuVenda.png"));
        btnMenuVenda.setIcon(i);
    }//GEN-LAST:event_btnMenuVendaMouseExited

    private void btnMenuVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVendaMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuVenda_Pressed.png"));
        btnMenuVenda.setIcon(i);
    }//GEN-LAST:event_btnMenuVendaMousePressed

    private void btnMenuVendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVendaMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuVenda_Hover.png"));
        btnMenuVenda.setIcon(i);
    }//GEN-LAST:event_btnMenuVendaMouseReleased

    private void btnMenuCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCadastroMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCadastro_Hover.png"));
        btnMenuCadastro.setIcon(i);
    }//GEN-LAST:event_btnMenuCadastroMouseEntered

    private void btnMenuCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCadastroMouseExited
        if ((!pnlSubMenu.isVisible()) || (!this.cadastro)) {
            ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCadastro.png"));
            btnMenuCadastro.setIcon(i);
        }
    }//GEN-LAST:event_btnMenuCadastroMouseExited

    private void btnMenuCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCadastroMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCadastro_Pressed.png"));
        btnMenuCadastro.setIcon(i);
    }//GEN-LAST:event_btnMenuCadastroMousePressed

    private void btnMenuCadastroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCadastroMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCadastro_Hover.png"));
        btnMenuCadastro.setIcon(i);
    }//GEN-LAST:event_btnMenuCadastroMouseReleased

    private void btnMenuConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuConsultaMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuConsulta_Hover.png"));
        btnMenuConsulta.setIcon(i);
    }//GEN-LAST:event_btnMenuConsultaMouseEntered

    private void btnMenuConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuConsultaMouseExited
        if ((!pnlSubMenu.isVisible()) || (this.cadastro)) {
            ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuConsulta.png"));
            btnMenuConsulta.setIcon(i);
        }
    }//GEN-LAST:event_btnMenuConsultaMouseExited

    private void btnMenuConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuConsultaMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuConsulta_Pressed.png"));
        btnMenuConsulta.setIcon(i);
    }//GEN-LAST:event_btnMenuConsultaMousePressed

    private void btnMenuConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuConsultaMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuConsulta_Hover.png"));
        btnMenuConsulta.setIcon(i);
    }//GEN-LAST:event_btnMenuConsultaMouseReleased

    private void btnMenuFornecimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecimentoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecimento_Hover.png"));
        btnMenuFornecimento.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecimentoMouseEntered

    private void btnMenuFornecimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecimentoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecimento.png"));
        btnMenuFornecimento.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecimentoMouseExited

    private void btnMenuFornecimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecimentoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecimento_Pressed.png"));
        btnMenuFornecimento.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecimentoMousePressed

    private void btnMenuFornecimentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecimentoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecimento_Hover.png"));
        btnMenuFornecimento.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecimentoMouseReleased

    private void btnMenuProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuProdutoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuProduto_Hover.png"));
        btnMenuProduto.setIcon(i);
    }//GEN-LAST:event_btnMenuProdutoMouseEntered

    private void btnMenuProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuProdutoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuProduto.png"));
        btnMenuProduto.setIcon(i);
    }//GEN-LAST:event_btnMenuProdutoMouseExited

    private void btnMenuProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuProdutoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuProduto_Pressed.png"));
        btnMenuProduto.setIcon(i);
    }//GEN-LAST:event_btnMenuProdutoMousePressed

    private void btnMenuProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuProdutoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuProduto_Hover.png"));
        btnMenuProduto.setIcon(i);
    }//GEN-LAST:event_btnMenuProdutoMouseReleased

    private void btnMenuFornecedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecedorMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecedor_Hover.png"));
        btnMenuFornecedor.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecedorMouseReleased

    private void btnMenuFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecedorMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecedor_Pressed.png"));
        btnMenuFornecedor.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecedorMousePressed

    private void btnMenuFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecedorMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecedor.png"));
        btnMenuFornecedor.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecedorMouseExited

    private void btnMenuFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFornecedorMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFornecedor_Hover.png"));
        btnMenuFornecedor.setIcon(i);
    }//GEN-LAST:event_btnMenuFornecedorMouseEntered

    private void btnMenuClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuClienteMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCliente_Hover.png"));
        btnMenuCliente.setIcon(i);
    }//GEN-LAST:event_btnMenuClienteMouseReleased

    private void btnMenuClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuClienteMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCliente_Pressed.png"));
        btnMenuCliente.setIcon(i);
    }//GEN-LAST:event_btnMenuClienteMousePressed

    private void btnMenuClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuClienteMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCliente.png"));
        btnMenuCliente.setIcon(i);
    }//GEN-LAST:event_btnMenuClienteMouseExited

    private void btnMenuClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuClienteMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuCliente_Hover.png"));
        btnMenuCliente.setIcon(i);
    }//GEN-LAST:event_btnMenuClienteMouseEntered

    private void btnMenuFuncionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFuncionarioMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFuncionario_Hover.png"));
        btnMenuFuncionario.setIcon(i);
    }//GEN-LAST:event_btnMenuFuncionarioMouseReleased

    private void btnMenuFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFuncionarioMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFuncionario_Pressed.png"));
        btnMenuFuncionario.setIcon(i);
    }//GEN-LAST:event_btnMenuFuncionarioMousePressed

    private void btnMenuFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFuncionarioMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFuncionario.png"));
        btnMenuFuncionario.setIcon(i);
    }//GEN-LAST:event_btnMenuFuncionarioMouseExited

    private void btnMenuFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuFuncionarioMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/menu/botaoMenuFuncionario_Hover.png"));
        btnMenuFuncionario.setIcon(i);
    }//GEN-LAST:event_btnMenuFuncionarioMouseEntered

    private void btnMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCadastroActionPerformed
        pnlSubMenu.setVisible(true);
        this.cadastro = true;
        pnlAgenda.setVisible(false);
        java.awt.event.MouseEvent me = new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, cadastro);
        btnMenuAgendaMouseExited(me);
        btnMenuServicoMouseExited(me);
        btnMenuVendaMouseExited(me);
        btnMenuConsultaMouseExited(me);
    }//GEN-LAST:event_btnMenuCadastroActionPerformed

    private void btnMenuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuConsultaActionPerformed
        pnlSubMenu.setVisible(true);
        this.cadastro = false;
        pnlAgenda.setVisible(false);
        java.awt.event.MouseEvent me = new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, cadastro);
        btnMenuAgendaMouseExited(me);
        btnMenuServicoMouseExited(me);
        btnMenuVendaMouseExited(me);
        btnMenuCadastroMouseExited(me);
    }//GEN-LAST:event_btnMenuConsultaActionPerformed

    private void btnMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuVendaActionPerformed
        pnlSubMenu.setVisible(false);
        this.cadastro = false;
        pnlAgenda.setVisible(false);
        java.awt.event.MouseEvent me = new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, cadastro);
        btnMenuAgendaMouseExited(me);
        btnMenuServicoMouseExited(me);
        btnMenuConsultaMouseExited(me);
        btnMenuCadastroMouseExited(me);
    }//GEN-LAST:event_btnMenuVendaActionPerformed

    private void btnMenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuServicoActionPerformed
        pnlSubMenu.setVisible(false);
        this.cadastro = false;
        pnlAgenda.setVisible(false);
        java.awt.event.MouseEvent me = new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, cadastro);
        btnMenuAgendaMouseExited(me);
        btnMenuVendaMouseExited(me);
        btnMenuConsultaMouseExited(me);
        btnMenuCadastroMouseExited(me);
    }//GEN-LAST:event_btnMenuServicoActionPerformed

    private void btnMenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAgendaActionPerformed
        pnlAgenda.setVisible(true);
        pnlSubMenu.setVisible(false);
        this.cadastro = false;
        java.awt.event.MouseEvent me = new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, cadastro);
        btnMenuServicoMouseExited(me);
        btnMenuVendaMouseExited(me);
        btnMenuConsultaMouseExited(me);
        btnMenuCadastroMouseExited(me);
    }//GEN-LAST:event_btnMenuAgendaActionPerformed

    private void btnAgendarServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarServicoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoAgendarServico_Hover.png"));
        btnAgendarServico.setIcon(i);
    }//GEN-LAST:event_btnAgendarServicoMouseEntered

    private void btnAgendarServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarServicoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoAgendarServico.png"));
        btnAgendarServico.setIcon(i);
    }//GEN-LAST:event_btnAgendarServicoMouseExited

    private void btnAgendarServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarServicoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoAgendarServico_Pressed.png"));
        btnAgendarServico.setIcon(i);
    }//GEN-LAST:event_btnAgendarServicoMousePressed

    private void btnAgendarServicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarServicoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoAgendarServico_Hover.png"));
        btnAgendarServico.setIcon(i);
    }//GEN-LAST:event_btnAgendarServicoMouseReleased

    private void btnAgendarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarServicoActionPerformed

    private void btnCancelarServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarServicoMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoCancelarServico_Hover.png"));
        btnCancelarServico.setIcon(i);
    }//GEN-LAST:event_btnCancelarServicoMouseEntered

    private void btnCancelarServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarServicoMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoCancelarServico.png"));
        btnCancelarServico.setIcon(i);
    }//GEN-LAST:event_btnCancelarServicoMouseExited

    private void btnCancelarServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarServicoMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoCancelarServico_Pressed.png"));
        btnCancelarServico.setIcon(i);
    }//GEN-LAST:event_btnCancelarServicoMousePressed

    private void btnCancelarServicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarServicoMouseReleased
        ImageIcon i = new ImageIcon(getClass().getResource("/salaovirtual/images/agenda/botaoCancelarServico_Hover.png"));
        btnCancelarServico.setIcon(i);
    }//GEN-LAST:event_btnCancelarServicoMouseReleased

    private void btnCancelarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarServico;
    private javax.swing.JButton btnCancelarServico;
    private javax.swing.JButton btnMenuAgenda;
    private javax.swing.JButton btnMenuCadastro;
    private javax.swing.JButton btnMenuCliente;
    private javax.swing.JButton btnMenuConsulta;
    private javax.swing.JButton btnMenuFornecedor;
    private javax.swing.JButton btnMenuFornecimento;
    private javax.swing.JButton btnMenuFuncionario;
    private javax.swing.JButton btnMenuProduto;
    private javax.swing.JButton btnMenuServico;
    private javax.swing.JButton btnMenuVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlSubMenu;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}
